- hosts: localhost
  roles:

  - common

  - role: VPC
    group_name: default
    inbound_rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "{{ localhost_IP }}/32"

  - role: EC2
    action_type: stop

  - role: instance_utils
    action_type: delete
