- hosts: localhost
  gather_facts: False
  tasks:
    - name: Gather remote facts
      ec2_instance_facts:
        region: eu-west-1
      register: ec2_facts

    - name: Print all instances status
      debug:
        msg: "Instance: {{item.0 }} with tags {{ item.1 }} is {{ item.2 }}"
      with_together:
        - "{{ ec2_facts.instances|map(attribute='instance_id')|list }}"
        - "{{ ec2_facts.instances|map(attribute='tags.Name')|list }}"
        - "{{ ec2_facts.instances|map(attribute='state.name')|list }}"

    - name: Add instances to Ansible groups in memory
      add_host:
        groups: "{{ item.1 }}, {{ item.2 }}, ec2"
        name: "{{ item.0 }}"
        state: "{{ item.2 }}"
        public_address: "{{ item.3 }}"
      with_together:
        - "{{ ec2_facts.instances|map(attribute='instance_id')|list }}"
        - "{{ ec2_facts.instances|map(attribute='tags.Name')|list }}"
        - "{{ ec2_facts.instances|map(attribute='state.name')|list }}"
        - "{{ ec2_facts.instances|map(attribute='public_dns_name_ip_address')|list }}"

    - name: Print all instances properties of Ansible groups in memory
      debug:
        msg: "Instance: {{ item }} in groups {{ ', '.join(hostvars[item].group_names) }} is {{ hostvars[item].state }}{% if hostvars[item].state == 'running' %} on address {{hostvars[item].public_address}}{% endif %}"
      with_items:
        "{{ groups.all }}"
