- name: Gather facts
  hosts: localhost
  tasks:
    - name: Gather facts
      ec2_remote_facts:
        region: eu-west-1
      register: ec2_facts
    - name: Get only running instance DNS names.
      debug:
        msg: "Instance: {{ item.0 }} has public DNS name: {{ item.1 }}"
      with_together:
        - "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='tags.Name')|list }}"
        - "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='public_dns_name')|list }}"
    - name: Add instances to running Ansible group in memory (not persistent between playbook runs).
      add_host:
        groups: "{{ item.0 }}"
        hostname: "{{ item.1 }}"
      with_together:
        - "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='tags.Name')|list }}"
        - "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='privatepublic_dns_name_ip_address')|list }}"
