- hosts: localhost
  gather_facts: False
  vars:
    region: eu-west-1
  tasks:
  - include_tasks: tasks/list_instances.yml state=['running']
  - include_tasks: tasks/add_running_instances_to_hosts.yml

- hosts: running
  remote_user: ubuntu
  gather_facts: False
  tasks:
    - name: test connection
      ping:
