- hosts: localhost
  roles:

  - key

  - get_localhost_IP
  - role: VPC
    group_name: default
    inbound_rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "{{ localhost_IP }}/32"
