- hosts: localhost
  roles:

  - common
  - key

  - role: VPC
    group_name: default
    inbound_rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "{{ localhost_IP }}/32"

  - role: VPC
    group_name: default_EFS
    inbound_rules:
    - proto: tcp
      from_port: 2049
      to_port: 2049
      group_name: default
