- hosts: localhost
  gather_facts: False
  vars:
    region: eu-west-1
  tasks:

  - name: Print all instances properties of Ansible groups in memory
    debug:
      msg: "Instance: {{ item.key }} [{{ ', '.join(item.value.group_names) }}] is {{ item.value.ec2_state }}{% if item.value.ec2_state == 'running' %} on address {{item.value.ec2_public_dns_name}}{% endif %}"
    with_dict: "{{ hostvars }}"
    when: item.value.ec2_state == 'running'

  - name: Add running instances to hosts group
    add_host:
      groups: running
      name: "{{ item.value.ansible_host }}"
      ansible_host: "{{ item.value.ec2_public_dns_name }}"
      key_name: "{{ item.value.ec2_key_name }}"
      key_file: "./{{ item.value.ec2_key_name}}.pem"
      ansible_python_interpreter: /usr/bin/python3
    with_dict: "{{ hostvars }}"
    when: item.value.ec2_state == 'running'

- hosts: running
  remote_user: ubuntu
  gather_facts: False
  tasks:
    - name: test connection
      ping:
