- hosts: localhost
  gather_facts: False
  tasks:
    - name: Print all instances properties of Ansible groups in memory
      debug:
        msg: "Instance: {{ item.key }} [{{ ', '.join(item.value.group_names) }}] is {{ item.value.ec2_state }}{% if item.value.ec2_state == 'running' %} on address {{item.value.ec2_public_dns_name}}{% endif %}"
      with_dict: "{{ hostvars }}"
      when: (state_filter is not defined) or (state_filter is defined and item.value.ec2_state in state_filter)
