- hosts: localhost
  roles:
  - { role: EC2, state: running }

- hosts: running
  roles:
  - { role: instance_utils, state: present }
  - aws_credentials
  - jupyter
  - { role: ssh_tunnel, state: running }
  - gitlab
