- hosts: localhost
  roles:
  - { role: EC2, action_type: start }

- hosts: running
  roles:
  - { role: instance_utils, action_type: create }
  - aws_credentials
  - jupyter
  - { role: ssh_tunnel, action_type: start }
  - gitlab
