- hosts: localhost
  gather_facts: False
  vars:
    region: eu-west-1
  tasks:
    - include_tasks: tasks/list_instances.yml state=['running']
    - include_tasks: tasks/add_running_instances_to_hosts.yml

- hosts: running
  gather_facts: False
  tasks:
    - include_tasks: tasks/start_jupyter.yml
      vars:
        instance_port: 8888
        local_port: 8888
    - include_tasks: tasks/stop_ssh_tunnel_from_localhost.yml
      vars:
        instance_port: 8888
        local_port: 8888
    - include_tasks: tasks/create_ssh_tunnel_from_localhost.yml
      vars:
        instance_port: 8888
        local_port: 8888
