- hosts: localhost
  gather_facts: False
  vars:
    region: eu-west-1
  tasks:

  - name: Print all instances properties of Ansible groups in memory
    debug:
      msg: "Instance: {{ item.key }} [{{ ', '.join(item.value.group_names) }}] is {{ item.value.ec2_state }}{% if item.value.ec2_state == 'running' %} on address {{item.value.ec2_public_dns_name}}{% endif %}"
    with_dict: "{{ hostvars }}"
    when: item.value.ec2_state == 'running'

  - name: Stop instances
    ec2:
      instance_ids: "{{ item.value.ec2_id }}"
      region: "{{ region }}"
      state: stopped
    with_dict: "{{ hostvars }}"
    when: item.value.ec2_state == 'running'
