- hosts: localhost
  tasks:
  - name: get localhost home directory
    local_action: command echo ~
    register: localhost_home
  - debug: msg="{{localhost_home.stdout}}"
  # tasks:
  # - s3_bucket:
  #     name: insighters.servant
  #     region: "{{ region }}"
