- hosts: localhost
  roles:
  - EC2

- hosts: running
  roles:
  - instance_utils
  tasks:
  - name: install git
    package:
      name: git
  - name: clone git repo
    vars:
      ansible_user: ec2-user
      gitlab_repo_name: recommender_system_back
      gitlab_repo_vendor: the_insighters
      gitlab_token: rJZoxBR_VVLQgpgafj94
    git:
      repo: "https://oauth2:{{ gitlab_token }}@gitlab.com/{{ gitlab_repo_vendor }}/{{ gitlab_repo_name }}.git"
      dest: "/home/{{ ansible_user }}/{{ gitlab_repo_name }}"
