- hosts: localhost
  roles:
  - EC2

- hosts: running
  roles:
  - instance_utils
  - aws_credentials
  - role: EFS
    targets:
    - subnet_id: "{{ hostvars.localhost.subnet.id }}"
      security_groups: "{{ hostvars.localhost.security_groups | selectattr('group_name', 'equalto', 'default_EFS') | map(attribute='group_id') | list }}"
