- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: tmp_key
    group: default
    instance_type: t2.micro
    image: ami-1b791862
    region: eu-west-1
    vpc_subnet_id: subnet-d521139c
  tasks:
    - name: Launch instance
      ec2:
        key_name: "{{ key_name }}"
        group: "{{ group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"
