- name: set default rules with localhost IP for inbound ssh protocol
  ec2_group:
    name: default
    description: "default VPC security group"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ localhost_IP }}/32"
    rules_egress:
    - proto: -1
      cidr_ip: 0.0.0.0/0
