- name: clear any ssh tunnel
  vars:
    instance_port: 80
  shell: ps -ef | grep -iE -- "ss[h].*{{ instance_port }}" | awk '{print $2}' | xargs kill -9
  ignore_errors: yes

- debug:
    msg: "{{ instance_address }}"

- name: start ssh tunnel and launch command
  vars:
    instance_port: 80
    local_port: 80
  shell: nohup ssh -N -p {{ instance_port }} {{ instance_address }} -L {{ instance_port }}:localhost:{{ local_port }} {{ instance_command }} &
  notify: stop ssh tunnel
