- name: Search for the latest Deep Learning Ubuntu AMI
  ec2_ami_facts:
    owners: 898082745236
    filters:
      name: "Deep Learning*Conda*Ubuntu*"
  register: ami_find

- name: Print search results
  debug:
    msg: "{{ item }}"
  with_items:
    "{{ ami_find.images }}"
