- name: start ssh tunnel from localhost
  shell: "nohup ssh -i {{ ansible_ssh_private_key_file }} -N {{ remote_user }}@{{ ansible_host }} -L {{ remote_port }}:localhost:{{ local_port }} &"
  delegate_to: localhost
