- name: get localhost IP
  command: curl http://checkip.amazonaws.com/
  register: curl_IP

- set_fact: localhost_IP="{{ curl_IP.stdout}}"

- name: print localhost IP
  debug:
    msg: "localhost IP is: {{ localhost_IP }}"
