- name: create ec2 key
  ec2_key:
    name: "{{ key_name }}"
  register: ec2_key

- name: save private key
  copy:
    content: "{{ ec2_key.key.private_key }}"
    dest: "{{ key_directory }}/{{ key_name }}.pem"
    mode: 0600
  when: ec2_key.changed
