- name: start jupyter
  shell: "nohup jupyter lab --NotebookApp.token={{ jupyter_token }} --NotebookApp.port={{ jupyter_port }} </dev/null >{{ remote_home }}/jupyter.log 2>&1 &"
  args:
    executable: bash
