- name: delete existing instance directory
  file:
    path: "{{ instance_utils_directory }}"
    state: absent
  delegate_to: localhost
  ignore_errors: yes
  when: state != 'present'

- name: create instance directory
  file:
    path: "{{ instance_utils_directory }}"
    state: directory
  delegate_to: localhost
  when: state == 'present'
