- include_tasks: instance_directory.yml

- include_tasks: ssh_connection.yml
  when: state == 'present'

- include_tasks: remote_ftp.yml
  when: state == 'present'

- include_tasks: sshfs_mount_umount.yml
  when: state == 'present'

- include_tasks: ssh_tunnel.yml
  when: state == 'present'

- include_tasks: install_htop.yml
  when: state == 'present'
