- name: create remote_ftp directory
  file:
    path: instance/remote_ftp
    state: directory
  delegate_to: localhost

- name: create remote_ftp config file
  template:
    src: ftpconfig.j2
    dest: instance/remote_ftp/.ftpconfig
  delegate_to: localhost
