- name: create remote_ftp directory
  file:
    path: "{{ instance_utils_directory }}/remote_ftp"
    state: directory
  delegate_to: localhost

- name: create remote_ftp config file
  template:
    src: ftpconfig.j2
    dest: "{{ instance_utils_directory }}/remote_ftp/.ftpconfig"
  delegate_to: localhost
