- name: create group with localhost IP for inbound protocol
  ec2_group:
    name: "{{ group_name }}"
    description: "{{ group_name }} VPC security group"
    vpc_id: "{{ VPC.id }}"
    rules: "{{ inbound_rules }}"
    rules_egress:
    - proto: -1
      cidr_ip: 0.0.0.0/0
  delegate_to: localhost
  register: group_output
