- name: create subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ VPC.id }}"
    az: "{{ availability_zone }}"
    cidr: "{{ subnet_CIDR }}"
    tags:
      Name: "{{ subnet_name }}"
  delegate_to: localhost
  register: subnet_output

- set_fact: subnet="{{ subnet_output.subnet}}"

- debug: msg="{{ subnet }}"
