- uri:
    url: http://checkip.amazonaws.com
    return_content: yes
  register: webpage
- set_fact: "localhost_IP={{ webpage.content.rstrip() }}"

- name: print localhost IP
  debug:
    msg: "localhost IP is: {{ localhost_IP }}"
