- name: Add running instances to hosts group
  add_host:
    groups: running
    name: "{{ item.value.ansible_host }}"
    ansible_user: "{{ remote_user }}"
    ansible_host: "{{ item.value.ec2_public_dns_name }}"
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ item.value.ec2_key_name}}.pem"
    region: "{{ item.value.ec2_region }}"
  with_dict: "{{ hostvars }}"
  when: item.value.ec2_state == 'running'
