- name: create new instance
  ec2:
    image: "{{ AMI_image_id }}"
    instance_type: "{{ EC2_instance_type }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    wait: yes
    exact_count: "{{ exact_count }}"
    instance_tags: "{{ instance_tags }}"
    count_tag: "{{ instance_tags }}"
    instance_initiated_shutdown_behavior: terminate
