- set_fact: exact_count=0
  when: action_type == 'stop'

- name: create or terminate instances
  ec2:
    vpc_subnet_id: "{{ subnet.id }}"
    group: "{{ group_name }}"
    assign_public_ip: yes
    image: "{{ AMI_image_id }}"
    instance_type: "{{ EC2_instance_type }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    wait: yes
    exact_count: "{{ exact_count }}"
    instance_tags: "{{ instance_tags }}"
    count_tag: "{{ instance_tags }}"
    instance_initiated_shutdown_behavior: terminate
