- name: Search for the latest Deep Learning Ubuntu AMI
  ec2_ami_facts:
    owners: "{{ AMI_owner }}"
    filters:
      name: "{{ AMI_name }}"
  register: AMI_find

- name: Print search results
  debug:
    msg: "{{ item.name }} | {{ item.image_id }}"
  with_items:
    "{{ AMI_find.images }}"

- name: Keep the first AMI result to use it
  set_fact: AMI_image_id="{{ AMI_find.images[0].image_id }}"
