- include_tasks: list_instances.yml
- include_tasks: list_subnet.yml
- include_tasks: list_group.yml
- include_tasks: find_AMI.yml
  when: AMI_image_id is not defined
- include_tasks: create_or_terminate_instance.yml
  when: (state == 'running') or (state == 'stopped')

- include_tasks: refresh_inventory.yml
- include_tasks: list_instances.yml
- include_tasks: add_running_instances_to_hosts.yml
  when: state != 'stopped'

- include_tasks: wait_for_ssh.yml
  when: state == 'running'
- include_tasks: list_instances.yml
  when: state == 'running'
